from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    BRIDGE_NOT_RUNNING = "BRIDGE_NOT_RUNNING"
    BRIDGE_UNREACHABLE = "BRIDGE_UNREACHABLE"
    BRIDGE_AUTH_FAILED = "BRIDGE_AUTH_FAILED"
    BRIDGE_CONFIG_INVALID = "BRIDGE_CONFIG_INVALID"
    BRIDGE_CONNECTION_DROPPED = "BRIDGE_CONNECTION_DROPPED"
    BRIDGE_SMTP_UNAVAILABLE = "BRIDGE_SMTP_UNAVAILABLE"
    MAIL_FOLDER_NOT_FOUND = "MAIL_FOLDER_NOT_FOUND"
    MESSAGE_NOT_FOUND = "MESSAGE_NOT_FOUND"
    ATTACHMENT_NOT_FOUND = "ATTACHMENT_NOT_FOUND"
    ATTACHMENT_BYTES_UNAVAILABLE = "ATTACHMENT_BYTES_UNAVAILABLE"
    INVITE_PARSE_FAILED = "INVITE_PARSE_FAILED"
    INVITE_UNSAFE_TO_RSVP = "INVITE_UNSAFE_TO_RSVP"
    INVITE_NOT_FOUND = "INVITE_NOT_FOUND"
    CALENDAR_UNREACHABLE = "CALENDAR_UNREACHABLE"
    CALENDAR_AUTH_FAILED = "CALENDAR_AUTH_FAILED"
    CALENDAR_DISCOVERY_FAILED = "CALENDAR_DISCOVERY_FAILED"
    CALENDAR_NOT_FOUND = "CALENDAR_NOT_FOUND"
    EVENT_NOT_FOUND = "EVENT_NOT_FOUND"
    EVENT_CONFLICT = "EVENT_CONFLICT"
    CONFIG_INVALID = "CONFIG_INVALID"
    SECRET_FILE_PERMISSIONS_INSECURE = "SECRET_FILE_PERMISSIONS_INSECURE"
    SQLITE_UNAVAILABLE = "SQLITE_UNAVAILABLE"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_IMPLEMENTED_SAFE_FALLBACK = "NOT_IMPLEMENTED_SAFE_FALLBACK"
    SMTP_SEND_FAILED = "SMTP_SEND_FAILED"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class InviteStatus(StrEnum):
    PENDING = "pending"
    ACCEPTED = "accepted"
    TENTATIVE = "tentative"
    DECLINED = "declined"
    CANCELED = "canceled"


class EventStatus(StrEnum):
    CONFIRMED = "confirmed"
    TENTATIVE = "tentative"
    CANCELED = "canceled"


class MailboxKind(StrEnum):
    FOLDER = "folder"
    LABEL = "label"


class SyncScope(StrEnum):
    MAIL = "mail"
    INVITES = "invites"
    CALENDAR = "calendar"
