from __future__ import annotations

from datetime import datetime
from typing import Protocol

from proton_agent_suite.domain.models import (
    CalendarInfo,
    ConnectorInfo,
    EventAttendee,
    EventInfo,
    FolderInfo,
    HealthCheckResult,
    InviteRecordView,
    MessageDetail,
    MessageSummary,
)
from proton_agent_suite.domain.value_objects import MailSendRequest


class CredentialStore(Protocol):
    def load_settings(self, profile: str | None = None, db_override: str | None = None) -> object: ...


class MailProvider(Protocol):
    def healthcheck(self) -> HealthCheckResult: ...
    def list_folders(self) -> list[FolderInfo]: ...
    def sync_folder(self, folder: str, since: datetime) -> list[MessageDetail]: ...
    def fetch_message(self, folder: str, uid: int) -> MessageDetail: ...
    def fetch_raw_message(self, folder: str, uid: int) -> bytes: ...
    def send_message(self, request: MailSendRequest) -> dict[str, str]: ...
    def mark_read(self, folder: str, uid: int) -> None: ...
    def mark_unread(self, folder: str, uid: int) -> None: ...
    def move_message(self, source_folder: str, uid: int, target_folder: str) -> None: ...
    def archive_message(self, source_folder: str, uid: int) -> None: ...
    def list_labels(self) -> list[str]: ...
    def add_label(self, source_folder: str, uid: int, label_name: str) -> None: ...
    def remove_label(self, message_id_header: str, label_name: str) -> None: ...
    def create_folder(self, name: str) -> FolderInfo: ...
    def rename_folder(self, old_name: str, new_name: str) -> FolderInfo: ...
    def delete_folder(self, name: str) -> None: ...


class CalendarProvider(Protocol):
    def healthcheck(self) -> HealthCheckResult: ...
    def discover(self) -> list[CalendarInfo]: ...
    def list_calendars(self) -> list[CalendarInfo]: ...
    def get_calendar(self, calendar_ref: str) -> CalendarInfo: ...
    def list_upcoming_events(self, days: int, calendar_ref: str | None = None) -> list[EventInfo]: ...
    def changed_since(self, since: datetime, calendar_ref: str | None = None) -> list[EventInfo]: ...
    def get_event(self, event_ref: str) -> EventInfo: ...
    def create_event(
        self,
        *,
        calendar_ref: str,
        title: str,
        start: datetime,
        end: datetime,
        timezone_name: str | None = None,
        description: str | None = None,
        location: str | None = None,
        organizer: str | None = None,
        organizer_common_name: str | None = None,
        attendees: list[EventAttendee] | None = None,
        status: str = "CONFIRMED",
        sequence: int = 0,
        uid: str | None = None,
    ) -> EventInfo: ...
    def update_event(
        self,
        event_ref: str,
        *,
        title: str | None = None,
        start: datetime | None = None,
        end: datetime | None = None,
        timezone_name: str | None = None,
        description: str | None = None,
        location: str | None = None,
        organizer: str | None = None,
        organizer_common_name: str | None = None,
        attendees: list[EventAttendee] | None = None,
        status: str | None = None,
        sequence: int | None = None,
    ) -> EventInfo: ...
    def cancel_event(self, event_ref: str) -> EventInfo: ...
    def delete_event(self, event_ref: str) -> None: ...
    def create_calendar(self, name: str) -> CalendarInfo: ...
    def update_calendar(self, calendar_ref: str, name: str | None = None) -> CalendarInfo: ...
    def get_connector_info(self) -> ConnectorInfo: ...
    def export_ics_url(self, calendar_ref: str | None = None) -> str | None: ...


class InviteParser(Protocol):
    def extract_invites_from_message(self, message: MessageDetail) -> list[InviteRecordView]: ...
